import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import { useRouter } from 'next/navigation';
import router from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    const [formData, setFormData] = useState({})
    

    async function saveEmployee(e) {
      e.preventDefault()
      
      const response = await fetch('/api/employee', {
        method: 'POST',
        body: JSON.stringify(formData)
      })

      return await response.json()
    }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>Employee Profile Creation</h1><br/>
        
        <form className={styles.form} onSubmit={saveEmployee}>
  <label>
    Name:<br/>
    <input type="text" name="name" placeholder='Enter Name' onChange={e => setFormData({ ...formData, name: e.target.value})}/>
  </label><br/><br/>
  <label>
    Role:<br/>
    <input type="text" name="role" placeholder='Enter Role' onChange={e => setFormData({ ...formData, role: e.target.value})}/>
  </label><br/><br/>
  <label>
    Phone Number:<br/>
    <input type="tel" name="phone_number" placeholder='Enter phone number' onChange={e => setFormData({ ...formData, phone_number: +e.target.value})}/>
  </label><br/><br/>
  <label>
    Email:<br/>
    <input type="mail" name="email" placeholder='Enter email' onChange={e => setFormData({ ...formData, email: e.target.value})}/>
  </label><br/><br/>
  <label>
    Age:<br/>
    <input type="number" name="age" placeholder='Enter age' onChange={e => setFormData({ ...formData, age: +e.target.value})}/>
  </label><br/><br/>
  <button type="submit" value="Submit" onClick={() => router.push('/tablepage')}>Submit</button>
</form>
</div>
      </main>
    </>
  )
}
